### ISSUE TITLE
firebase-admin reference missing

### ISSUE THREAD

**Issue by edlectrico** [pakmingwCorp/dialogflow-demo#1]
The firebase-admin npm package is missing in the package.json file. Otherwise the fulfillment code can't be deployed within Dialogflow:
+ "firebase-admin": "^6.2.0"

https://github.com/pakmingwCorp/dialogflow-demo/blob/master/firebase/firebase/functions/package.json

**Comment by pakmingwCorp** [comment]
Hi there, I've just fixed this -- you should see it in the last commit. Thanks again for finding this.
